# Generated by Django 2.0.2 on 2020-05-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Project', max_length=200),
            preserve_default=False,
        ),
    ]
