# Generated by Django 2.0.2 on 2020-05-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200521_0516'),
        ('jobs', '0003_auto_20200521_0515'),
    ]

    operations = [
    ]
