# Generated by Django 2.0.2 on 2020-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
