# Generated by Django 2.0.2 on 2020-05-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='image',
        ),
    ]
